#!/bin/bash
echo Enter IP address of this node
read DEVICE_IP
echo "$DEVICE_IP - device ip."
echo Enter port of this node
read DEVICE_PORT
echo "$DEVICE_PORT - device port."

export HOST="${DEVICE_IP}"
export PORT="${DEVICE_PORT}"
echo ======================================
echo Enter IP address of the boot node aka. the peer you want to connect to
read BOOT_DEVICE_IP
echo "$BOOT_DEVICE_IP - device ip."
export HOST="${DEVICE_IP}"
echo Enter port of this boot node
read BOOT_DEVICE_PORT
echo "$BOOT_DEVICE_PORT - device port."

export PEER_ADDR="${BOOT_DEVICE_IP}"
export PEER_PORT="${BOOT_DEVICE_PORT}"
node peer.js
